### ISSUE TITLE
.env.example file (and others) not present on prod

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#107]
Following the steps outlined in [Deploy to Digital Ocean](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/deploy-to-digital-ocean.md), I SSHed into my Droplet, went to the root directory (`cd /var/www/html`), cloned the project from Github (`git clone git@github.com:baugh20s/p4.git`), ran `composer install --no-dev` which successfully added the vendor directory, ran the two permission commands for the storage and cache directories, then attempted to copy the .env.example file but got a 'no such file or directory' message back. I then realized that I was missing several files compared to the example video and notes:

- .env.example
- .gitattributes
- .gitignore

Here are the results of my clone to prod:
![clone from git](https://user-images.githubusercontent.com/20144373/48980665-17385e00-f09a-11e8-991d-38236e5660e8.png)

And the results of my composer install command:
![install no dev](https://user-images.githubusercontent.com/20144373/48980595-4a2e2200-f099-11e8-9911-b67393c042d0.png)

And the following commands with the no such file found message:
![no such file](https://user-images.githubusercontent.com/20144373/48980612-69c54a80-f099-11e8-9dba-26034b762aa8.png)

I assume I can just tell it to push those files specifically to prod, as they are present on the local version, but I'm wondering if I did something incorrectly or just missed a step along the way. I looked back through the notes but couldn't identify what that might be, and I don't recall this happening for project 3 or the foobooks example.

**Comment by susanBuck** [comment]
Looking at your repository (https://github.com/baugh20s/p4) those files are missing, so it makes sense they would not be present on production after cloning.

The question, then, is why they're missing.

When you created this project, did you A) create it using the `composer create-project` command (as described [here](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/new-laravel-app.md)) or did you B) create it by copying a previous project?

If B - All the files you're missing begin with a period, indicating they're hidden files. If you copied from a previous project via drag and drop, it's possible you missed those files because they weren't showing in your finder window.

If that's the case, a better way to do the copy would be via command line (`cp old-project-dir-name new-project-dir-name`) to make sure all files are included.

**Comment by baugh20s** [comment]
I did it using the `composer create-project laravel/laravel p4 "5.7.*" --prefer-dist` command

**Comment by susanBuck** [comment]
Hm, interesting! I can't think of why those files would be excluded. 

When you do a `git status` locally, is it showing those files as not yet added?
