### ISSUE TITLE
User uploaded photos in Laravel directory structure and DB

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#114]
Good afternoon!

If our app is mean to allow the user to input an image rather than referencing a URL, is there a best practice/place for saving that image in Laravel and on the DB?  I am assuming that the DB will contain a reference to the photo but am uncertain about where the file should actually end up to be accessed (in `resources/` or in `storage/`.  I remember this feature being mentioned in an earlier lecture video but would appreciate any advice.

Tks!

**Comment by susanBuck** [comment]
There are different approaches to this -

Regardless, we know that the images need to be accessible via `/public` since that's the directory the browser has access to.

### Approach 1
[The public disk](https://laravel.com/docs/5.7/filesystem#the-public-disk)
Store files in `storage/app/public` (or some subdirectory of that) and make them web accessible at `/public` via a symbolic link. This can be done via the command `php artisan storage:link`

### Approach 2
Just put the files somewhere directly in `/public`, e.g. `/public/uploads`




On a related note, if dealing with uploads, be sure to read this for some useful tools: [File Storage](https://laravel.com/docs/5.7/filesystem#storing-files).

**Comment by jessupjs** [comment]
Thanks!!
