### ISSUE TITLE
PHP -> blade syntax in views. How to correctly switch over?

### ISSUE THREAD

**Issue by q0w9e8r7t6y5** [susanBuck/dwa15-fall2018#133]
One common complaint in my peer reviews of P3 (using same base for P4) is that I had a little php on my blade views.

Project link: https://github.com/q0w9e8r7t6y5/p3

Views page: https://github.com/q0w9e8r7t6y5/p3/blob/master/resources/views/order.blade.php

Specifically, some pieces like:

`
td>Topping:</td>
                <td> <?php if (!$toppings) {
                        echo "None";
                    } else {
                        echo ucwords(join(', ', $toppings));
                    }
                    ?>
                </td>
`

and 

`<?php
    $type = $_GET['type'] ?? null;`

   ` $fill = $_GET['fill'] ?? null;
    ?>`

I tried everything I could find online to get these to work without having to resort to php and couldn't get it work properly. Does anyone have any pointers on how to switch over statements like this into blade syntax?

Thanks,
Sishir

**Comment by susanBuck** [comment]
For this line:
```
<?php if (!$toppings) { echo "None"; } else { echo ucwords(join(', ', $toppings)); } ?>
```

We could re-write it like so:
```php
{{ (!$toppings) ? 'None' : ucwords(join(', ', $toppings)) }} 
```

Techniques used:
+ [Blade curly braces to echo content](https://laravel.com/docs/5.7/blade#displaying-data)
+ [Ternary operators (syntactic sugar)](https://github.com/susanBuck/dwa15-fall2018/blob/master/php/syntactic-sugar.md)

Example for reference: [foobooks > edit.blade.php > ln 31](https://github.com/susanBuck/foobooks/blob/master/resources/views/books/edit.blade.php#L31)


For this code:
```
<?php $type = $_GET['type'] ?? null;
$fill = $_GET['fill'] ?? null; ?>
```

Rather than defining `$type` and `$fill` in the view, I'd define it in the controller and make it available to the view.

Let me know if you have any follow-up questions about the above techniques.
