### ISSUE TITLE
validator not consistent

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#15]
Hi,

When I paste my html code in validator I get only one error but when I paste my production url I get 5 errors. Should not both be same?

Thanks
Hemant

**Comment by susanBuck** [comment]
Can you provide an example of the code you're pasting in, and the production URL you're validating?

**Comment by hemantbajpai** [comment]
When I paste my html code in validator I get following error:

Saw <?. Probable cause: Attempt to use an XML processing instruction in HTML. (XML processing instructions are not supported in HTML.) 

Why is this happening?

**Comment by susanBuck** [comment]
@hemantbajpai Can you provide an example of the HTML code you're pasting? We need to see your code in order to give you insight into why you're getting that error.

I suspect you're trying to paste in some PHP code - which will always throw errors. The w3 validator is only for HTML code, i.e. the code the browser sees.

If you want to copy/paste your code for testing, use the "View Source" feature of your browser to grab the underlying HTML, with any PHP already processed.

**Comment by hemantbajpai** [comment]
Thanks
