### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2018#2]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. **Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - this is my 11th semester teaching this course at the Extension School. In the past, I've taught at various other colleges - Wellesley College, UPenn, UMiami. When working in industry I was the head developer for an online e-commerce store - [Photojojo](http://photojojo.com). 

Up until last year, I was the co-president of an initiative called the [Women's Coding Collective](https://thewcc.com), which was aimed at getting more women and other under-represented minorities into programming. 

These days, I've been splitting my time between teaching with the Ext. School and working on [Introze](https://introze.online) (an app you may be familiar with because I asked you to use it in the course welcome email. :)

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by jessupjs** [comment]
# Good evening! :smile:
It is a pleasure to meet you, and I look forward to reading more auto-biographies!

Mine is not very remarkable, I'm afraid.  I am a VA native who spent most of his career working in artisan design and social business in E Africa.  When my wife and I discovered she was with child, we returned to the US for the birth of our daughter (now 2), and I've been looking to build a bridge between the two places since.

For a bunch of reasons, web design and development appeared as the right tool for building that bridge, and that's why I'm here!

I'm also taking **CSCI E-3**  _Introduction to Web Programing Using JavaScript_ from HE and _Java 2_ from a nearby community college (to save some 💰), while working part-time and watching baby.

Look forward to a ***DYNAMIC*** 💥 term!
j

**Comment by vanillacandy** [comment]
Hi,
I work as a software developer in South Carolina, Boeing. I code in various programming languages for my job, and before this I studied in Mathematics in college. To become a computer developer with math background can be easy and hard at the same time, but I am excited to learn computer since I think it's practical to understand mathematics models. 
Outside of work, my passion is in music, I have played the classical piano for ten more years, and I have played Beethoven, Bach, Liszt, and Debussy...etc. I am still hoping to learn guitar one day and start a band. 
I am looking forward to this class since this class teaches students how to write a web app, and I think it'll be useful to my job.

**Comment by dickblair** [comment]
Howdy classmates,
My name is Dick Blair and I am a husband and a father of 2 originally from Philadelphia, but now living in San Antonio Texas.  I retired from the Army and started working as a Software Developer.  Prior to the Army I studied German, which I have since forgotten.  I am trying to use my GI Bill to study software engineering, and this course is a part of that journey.
Nice to meet you all.
-Dick

**Comment by mdeforest** [comment]
Hello everyone!

My name is Michaela DeForest. I currently work as a software developer in Malvern, Pennsylvania and am living in Philadelphia. I graduated with a BA in Computer Science in 2017 and am beginning the path of gaining my Master's in Software Engineering. 

While I am taking this class to fulfill a requirement, I chose it in hopes that it helps me in my job. I have had to learn a lot about web application development on my own while building a few Ruby on Rails apps for work. I am interested in gaining some formal web application development skills.

My hobbies include playing violin, playing basketball, and attending hackathons. 

I look forward to getting to know all of you!

Michaela

**Comment by calivine** [comment]
Hey everyone,

I'm Alex Caloggero. I'm from just outside of Boston, MA and currently work as a prospect researcher at Tufts University. About a year ago I took the online course, CS50x, which is Harvard's intro to Computer science course. I discovered that I really loved programming and design thinking and I've also had an interest in computers/technology since I was a kid. 

I completed CS50 and continued my learning with other online classes through EDx and have also worked on my own personal projects, learning and absorbing all that I can. I want to make a shift career-wise towards software development and this is my first big step! Great to meet you all and excited to get started!

Alex

**Comment by DoryAzar** [comment]
Hi everyone,

I am Dory Azar. I am originally lebanese canadian. I moved to Cambridge 6 years ago to lead the UX department at Kronos. 

I have a background in Computer Engineering and I continued in Industrial Engineering with a focus on User Experience Design. I am now enrolled in the Digital Media Design program at Harvard Extension.

Coding is a hobby of mine among others. I also love travelling (I try to visit at least one new city every year), running, tennis, skiing, reading, not to mention good restaurants in good company :).

I look forward to working with all of you!
D.

**Comment by mihika-shilpi** [comment]
Hey...Namaste...Bonjour! 
I'm from Bombay, India, but now work at a package design and branding agency in Paris, France as a Junior Art Director; where I'm learning about colours, cheese, inverted french words and how to live the European relax. I'm also an ALB student at Harvard Extension School, concentrating in Math. 
I plan to minor in Computer Science and Digital Media, and have always enjoyed (an admittedly basic level of) web development, so here's to furthering that! 
Aside from growing my design book collection, I’m also a bit (a lot) of a theoretical math geek, love cooking and eating, am infected by the travel bug and think a lot about education.
Looking forward to the semester!
Mihika

**Comment by pausman** [comment]
Hello all!
I live in the Boston area and currently work in the IT field.  I have taken a few CS courses at Harvard Extension while thinking about pursuing a masters degree in Computer Science but this is the first one that is online only.  I will miss meeting you all in person on a weekly basis.  I am excited to take this course because I have always wanted to learn the PHP framework.  
My passions outside of this class are traveling and coffee.  What a combination!
Pat

**Comment by satyapalvadi** [comment]
Hello everyone,

I am Satya. I am originally from India moved to the US for my Masters in CS 15 years ago. Currently, working as a software developer at a company just outside of Boston. This is my first Harvard Extn course.  I am excited to learn PHP and let's see how it goes :-) 

I have a 5 year active boy who keeps me on my toes all the time. His first day of Kindergarten is today and my first day of PHP class is also today !!!.

~Satya

**Comment by fpizzuta** [comment]
Hello,

My name is Frank Pizzuta. I live in Pennsylvania and have worked for a financial company for the last 25 years. I got my undergrad at Rutgers in CS and History. I have an MS in CS from Villanova, a Masters in Software Engineering from Penn State, and a MS in Data Analytics from Carnegie Mellon. I am a life long learner but have mostly focused on the back end and infrastructure side of things. I am enrolled in the Harvard Digital Media Program to increase my front end knowledge and simply try something new. I look forward to working with everyone this semester.

**Comment by khaliqakhan** [comment]
Hello everyone,
My name is Khaliq. I live in London, England, but am from Wisconsin, US. I have a bachelors from University of Wisconsin, where after some soul searching, I graduated with a bachelors in MIS, Finance and a minor in CS. A few years back, I decided to deepen my formal skills in CS and got a Post Graduate degree from University of Liverpool, England. Continuing with the theme of formal education in CS, I am now looking to broaden my skills in how to best utilise technology for user engagement / customer experience development. 
This is my first course at HU and look forward to working and learning from all of you.

**Comment by pingji00** [comment]
Hi all,

My name is Ping Ji, a designer work in the Boston area. I'm working with a lot of HTML/CSS/JS stuff, now I'd like to learn more about the back end. This is my 4th course at HES, hope everything's going well with the team.

I like build things, not only on paper/screen, but also in real life, so I'm a weekend woodworker as well.

**Comment by hemantbajpai4** [comment]
Hi all,

My name is Hemant Bajpai. I recently moved to seattle from boston. I am from mechanical background doing job in software industry. I am pursuing masters from Harvard extension school and this is my 10th course. 

I am looking forward to learning dynamic web application concepts from all of you.

**Comment by ningchen8743** [comment]
Hello Everyone!

My name is Ning Chen, I am originally from Beijing, China. After several years of study and working in the US since 2011, I am currently living in the upstate NY with my husband. In the past few years I have been working as a GIS analyst for Norfolk Southern Corp in Atlanta, GA. Through work as well as self taught I gained some understanding of Python, HTML and CSS. I took the introduction to JavaScript course in the summer, and hopefully DWA could help expand my understanding towards web programming from server-side! :)

I love to spend my spare time practicing harp on daily basis, and yoga+swimming are my choices of exercise. I studied urban design in college so field sketch has always been a hobby whenever I travel to somewhere. Below is a sketch I did during my recent trip to UK this year:)
![wechat image_20180908112525](https://user-images.githubusercontent.com/38412041/45255792-445a5780-b35a-11e8-95d4-3979007cc7b1.jpg)

Look forward to learning from everyone in this class!

Ning

**Comment by SandiAnderson** [comment]
Hi everyone,
I'm Sandi (Sandra). I live and work in Southern California with my husband and 3 dogs. I have been in the IT industry for ages and have previously worked in front end and backend development before switching to the analysis side. I am taking some courses as refreshers and to learn new technologies, one of which is PHP. Looking forward to working with everyone!

**Comment by Sud-B** [comment]
Hello :)!

I'm Sudhir. Live in NYC. Import from Sydney, Australia. Doing a Grad Cert in Web Technology after over 20 years in Banking/Finance because I started finding the web a lot more interesting than Finance and want to change careers. I love what I've learnt so far and look forward to learning more and creating interesting, dynamic webpages. 

Academically, I have a Bachelor's degree in Physics from Pune University in India and Master in Applied Finance from University of Melbourne in Australia.

Let's do wonderful things together out here!!

**Comment by jpersson74** [comment]
Hello, my name is Josh and I live in Rhode Island. This is my third course out of five for the Web Technologies Graduate Certificate. While not chasing around our six year old twins, I work in the Geospatial Group for the engineering company WSP creating maps and mapping products from aerial imagery. I'm hoping the skills I'm learning can help our Group deliver our products over the web.

**Comment by venkateshmantha** [comment]
Hello everyone!

I am Venkatesh Mantha, a Software Engineer in Boston. I am originally from India, moved to US couple of years ago to pursue Masters in Computer Science. This is my first course from the Extension school and I aim to graduate with an ALM in Information Management Systems. I believe in continuous learning and revel in interacting with people from different backgrounds. Worked with various software technologies previously and I would love to add PHP to the list. 

Looking forward!

**Comment by summerxwang** [comment]
Hi everyone! My name is Summer and I'm a PM in Seattle. As a PM, I don't code as much as I would like to, so I'm taking this class to brush up on my skills and learn more about different technologies. Excited to meet you all!

**Comment by josh-lim1234** [comment]
Hello everyone!

My name is also **Josh"" but I live in _Singapore_. I mainly chose this course to learn more as skills like programming can be useful in the future. Looking forward to working with you all!

**Comment by xmansimon** [comment]
Hi all!
My name is Simon Su. I just transferred my career from banking to software engineering. Hopefully, this course will solidify my knowledge on web application development. Looking forward to working on interesting projects.

Best,
Simon Su

**Comment by malrice** [comment]
Hello everyone, 
My name is Mallory, and I have been learning, living, and working in Boston for about 12 years. I work as a staff assistant at Harvard Med, and am taking this class to expand my web knowledge!  So far it seems like most of what we'll be covering is largely new to me, so I'll probably be on the issues forum a lot ;) 
Mallory

**Comment by ccrane** [comment]
Hi all :)

My name is Chris Crane. I living in Newfoundland, Canada, with my wife and 3 kids. For the past 5 years I have been employed as Manager of IT for the Newfoundland and Labrador English School District, and as a Senior Systems Analyst for 13 years prior to that. What seems like ages ago I completed my Bachelors Degree in Computer Science and Applied Mathematics.  I am really looking forward to interacting with all of you over the next few months as we work our way though the course.

All the best,
Chris

**Comment by viettnguyen** [comment]
Hi all,

Born and raised in Canada. I currently live in Boston. I have experience programming in different languages and I look forward to having a structured way of learning web development.

Best,
Viet

**Comment by noweber** [comment]
Hi, Everyone,

I live in Saint Paul, Minnesota and work as a software engineer. I'm excited to keep learning and I'm taking this course to expand skills I don't use directly in my job.

Looking forward to learning with all of you.

Best,

Owen

**Comment by chantalthomas** [comment]
Hello!

My name is Chantal Thomas I am from Washington, D.C. I have a bachelor's degree in Computer Engineering and I am pursuing  the Digital Media Design program at Harvard Extension. I currently work at Booz Allen Hamilton as a Software Engineer. I decided to take this class because I want to be able to build more than just a static webpage. I am really looking forward to expanding my knowledge in the realm of developing on the web.

Aside from development, I love traveling! I also referee basketball at a high level.

**Comment by dnoren32** [comment]
Hey Everyone,

I'm Alexander. I live in Southie. I have a Bachelor's in Accounting and am trying to build a software solution for a startup. I'm taking this course to get a better understanding for what goes into web development. I have taken a half dozen coding courses through my undergrad and graduate work (java, ADA, javascript). 

Looking forward to a great semester!

**Comment by baugh20s** [comment]
Hi everyone,

I'm Sarah and I work at an online software company in Somerville, Massachusetts. I'm in Client Services and looking to move into a more technical role, so I've taken a few courses through Harvard Extension.

In my free time, I like to work out, learn piano (just started this year), and find new things to do with friends in the city!

**Comment by 1234tech** [comment]
Hello classmates!

My name is Schermann and I use they/them/their pronouns.  I’m currently living in Slippery Rock, Pennsylvania.  I’m pursuing an ALM in Digital Media Design at Harvard.  My background includes both music (education and performance) as well as tech (computer repair and web design).  

I enrolled in this course because future projects will include work on both the client side and the server side.  I thought this would be a nice introduction to the server side since I can already create web-sites using HTML, CSS and Javascript.

**Comment by T-Waddell** [comment]
Hi all! I'm Tara, and I'm part of the Product Management team at a billing software company in Omaha, NE. I've also done sales support, marketing, and technical documentation for software, and am finally learning to code. I've completed the Front-End Web Development certificate and am working on a Masters in Digital Media Design. I'm interested in gaining some server-side skills to add to my front-end experience. Looking forward to the class!
