### ISSUE TITLE
MAMP 404 Error for http://localhost "The requested URL / was not found on this server."

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#20]
Hi,

I am trying to complete the local domain setup, and for some reason when I go to http://localhost, MAMP will say "The requested URL / was not found on this server." Any ideas how to fix this? When I was going through the lectures and creating the hello-world root, it worked fine.

**Comment by cpowell1** [comment]
Here it is!

#
# Virtual Hosts
#
# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at 
# <URL:http://httpd.apache.org/docs/2.2/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

#
# Use name-based virtual hosting.
#
NameVirtualHost *:80

#
# VirtualHost example:
# Almost any Apache directive may go into a VirtualHost container.
# The first VirtualHost section is used for all requests that do not
# match a ServerName or ServerAlias in any <VirtualHost> block.
#
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/Applications/MAMP/Library/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "/Applications/MAMP/Library/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error_log"
    CustomLog "logs/dummy-host2.example.com-access_log" common
</VirtualHost>



<VirtualHost *:80>
    ServerName hello-world.loc
    DocumentRoot /Applications/MAMP/htdocs/hello-world
    <Directory /Applications/MAMP/htdocs/hello-world>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>

**Comment by susanBuck** [comment]
Thanks! (FYI I edited your post to add markdown formatting so the vhosts file was easier to read).

Here's what I believe is happening -

Now that you've updated your MAMP apache config to use the vhosts.conf file, it's referring to that file for instructions on what to do when visiting `http://localhost`. This is in contrast to what it was originally doing (pre-vhosts config), which was mapping `http://localhost` based on whatever you set the document root to be in the MAMP interface.

To fix this, you want to follow the instructions described here:
https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/local-domain.md#fixing-httplocalhost

Note that in those instructions, it says the following:

> After you make the above change you'll notice that http://localhost no longer works as expected— instead of pointing the document root you configure in MAMP/XAMPP, it will start pointing to the first VirtualHost block in your httpd-vhosts.conf file.

Based on that, looking at your vhosts config, the first virtual host block is pointing to `/Applications/MAMP/Library/docs/dummy-host.example.com` which, as expected, does not exist. As a result, I believe that's why you're seeing the `"The requested URL / was not found on this server."` error.

Following the steps in the above directions should set you up so that you have `localhost` configured to point to the directory of your choice.

**Comment by cpowell1** [comment]
I am so sorry, I will pay attention to the Markdown syntax in future posts. Also, I got it to work. I had followed along in the lectures, and then I tried to start again with the notes for P1, and I didn't realize the extra code was needed to point to the htdocs. Thank you!

**Comment by susanBuck** [comment]
Glad that sorted it out! 

I did omit those steps in the lecture in the interest of time since it's not really necessary to have `localhost` functioning once you get local domains set up for each individual project. Given that, I can understand how it might have been missed.
