### ISSUE TITLE
Project 1: Non responsive PHP

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#40]
Hello, my PHP code won't do anything. I've pasted it below. Any suggestions/thoughts?

      <?php
	$qnumber = (rand(1,3));
	 if ($qnumber == 1);	{ 
	echo "The secret of getting things done is to act!	Dante Alighier ";
	}
	<elseif ($qnumber == 2); {
	echo "I wept not, so to stone within I grew.	 Dante Alighieri ";
	}
	elseif ($qnumber == 3); {
	echo "The secret of getting things done is to act!	 Dante Alighieri ";
	}
	endif;
	?>

**Comment by susanBuck** [comment]
Are you getting any errors when you run this code?
If so, what are they?
If not, review the notes on [error reporting and configs](https://github.com/susanBuck/dwa15-fall2018/blob/master/php/error-reporting-and-configs.md) to make sure your error reporting is configured correctly.

**Comment by Sud-B** [comment]
I'll re-check

**Comment by Sud-B** [comment]
However, the HTML validator has this error ; te:</h2>↩  ↩  <?php↩	$qnumber for the very first line of the PHP block. The HTML has no errors.

**Comment by susanBuck** [comment]
@Sud-B - The HTML validator should only be used to validate the HTML code output to the browser, it should never see PHP code. Review posts #15 and #25 for info on this.

Line 6 is this:

```php
<elseif ($qnumber == 2); {
```

Specifically, it says the problem is with the `<` character. Review the notes on [Conditionals](https://github.com/susanBuck/dwa15-fall2018/blob/master/php/conditionals.md) and compare and contrast how you've written it to the examples.

**Comment by Sud-B** [comment]
Thanks Susan. That < snuck by :). I've changed the code to this and now have no errors but it still won't work on my laptop. The HTML and CSS work.

<?php
	$qnumber = (rand(1,3));
	 if ($qnumber == 1)	{ 
	echo "The secret of getting things done is to act!	Dante Alighier ";
	}
	elseif ($qnumber == 2) {
	echo "I wept not, so to stone within I grew.	 Dante Alighieri ";
	}
	else {
	echo "The secret of getting things done is to act!	 Dante Alighieri ";
	}
  ?>

**Comment by Sud-B** [comment]
<?php
	$qnumber = (rand(1,3));
	 if ($qnumber == 1)	{ 
	echo "The secret of getting things done is to act!	Dante Alighier ";
	}
	elseif ($qnumber == 2) {
	echo "I wept not, so to stone within I grew.	 Dante Alighieri ";
	}
	else {
	echo "The secret of getting things done is to act!	 Dante Alighieri ";
	}
  ?>

**Comment by susanBuck** [comment]
Can you be more specific about how it's not working. For example, is it not producing the expected output? If so, what output is it producing and how is it different from what you're expecting?

Also, please share the revised code - you've made some changes, so now we need to know exactly what you're working with in order to continue to help troubleshooting.

**Comment by Sud-B** [comment]
The revised code is provided below. The webpage generated stops after the heading for random quotes without showing a quote, which the PHP code should generate. I've got the website up on dreamhost to test out for now and here is a link so you could see what is happening: http://blink.dreamhosters.com/p1dwa/
<?php
	$qnumber = (rand(1,3));
	 if ($qnumber == 1)	{ 
	echo "The secret of getting things done is to act!	Dante Alighier ";
	}
	elseif ($qnumber == 2) {
	echo "I wept not, so to stone within I grew.	 Dante Alighieri ";
	}
	else {
	echo "The secret of getting things done is to act!	 Dante Alighieri ";
	}
  ?>

**Comment by Sud-B** [comment]
<?php
	$qnumber = (rand(1,3));
	 if ($qnumber == 1)	{ 
	echo "The secret of getting things done is to act!	Dante Alighier ";
	}
	elseif ($qnumber == 2) {
	echo "I wept not, so to stone within I grew.	 Dante Alighieri ";
	}
	else {
	echo "The secret of getting things done is to act!	 Dante Alighieri ";
	}
  ?>
I pasted the code again.

**Comment by susanBuck** [comment]
@Sud-B - I'm sorry, I'm not seeing the revised code you said is provided below?

**Comment by susanBuck** [comment]
Follow-up, I just saw you emailed me the code. Looking at it now.

**Comment by susanBuck** [comment]
I was able to get your code to work on my end - because it required some code re-formatting, I thought it'd be easier to show than to tell, [so here's a brief video explaining](https://www.youtube.com/embed/ZN9pIzBwqp4?rel=0&showinfo=0).

Take a look at that, re-format/clean-up your code and see if that improves things. If not, follow-up and let us know and we'll continue to troubleshoot.

**Comment by DoryAzar** [comment]
yes it should be index.php

**Comment by Sud-B** [comment]
Thank you. Works perfectly now :)
