### ISSUE TITLE
Separation of Concerns - how to influence style/CSS from PHP

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#42]
Good afternoon!

It seems like I remember from the videos that PHP was used in the HTML document to modify the style of an element using inline code.  In terms of considering "separation of concerns", is it acceptable to control CSS in the HTML attributes, or later on will we be learning how to use PHP to adjust CSS properties more directly?

Many thanks!

**Comment by susanBuck** [comment]
To influence CSS from your PHP logic, you can utilize CSS classes and/or ids. There's different approaches to how you do this...

### Approach A
For example, let's say you're building a math game and you want to check the user's answer and let them know if they got the answer correct or not. Your PHP Logic code could look like this:

```php
$correct = $_GET['answer'] == 542;

if($correct) {
    $msg = 'You got it! Nice work.';
    $class ='correct';
}
else {
    $msg = 'That answer is incorrect; please try again';
    $class = 'incorrect'; 
}
```

Note how there's a variable set called `$class` that is set to `correct` or `incorrect`.

Then, in your display, you can output this `$class` like so:
```html
<div class='<?=$class'>'> 
    <?=$message ?>
</div>
```

Of course, you'd want some corresponding CSS to set the properties for these classes:

```css
.correct {
    color:green;
}

.incorrect {
    color:red;
}
```

### Approach B (Improved)
The above example works, but it's not super ideal because it does dictate what the language of the message is in the logic code, which arguably should be in the display code. So another approach would be to not dictate the `message` or `class` in the logic code, and instead simply pass on whether it was correct or not, letting the display file handle the rest:

```php
<?php if($correct): ?>
    <div class='correct'>
        You got it! Nice work
    </div>
<?php else: ?>
    <div class='incorrect'>
        That answer is incorrect; please try again
    </div>
<?php endif; ?>
```



## Bonus tip
A useful guide when deciding what should happen in the display vs logic files is to imagine you're working on a team that has front-end developers and back-end developers.

Imagine the front-end developers can only edit display-related files (HTML/CSS).
And the back-end developers can only edit the logic-related files.

You want to aim to write your code so that each developer can do their job without having to edit the files that "belong" to the other developer.

For example, if the boss told the front-end developer they wanted the language on the correct message to change from `You got it! Nice work.` to `Correct!`, the front-end developer would not be able to do that in their code files if we went with Approach A.

**Comment by jessupjs** [comment]
A quick follow-up more specific to my project (rough draft@ [Github](https://github.com/jessupjs/p2) / [Production](http://p2.jjessup.me/)).  

Basically I want to recolor my divs with rgba() values based on the user's input, so we're talking about 30 possible colors for 8 different fields (each unique bc I'm using CSS-controlled shapes), which would require adding 240 classes into my CSS file in order to handle the submission results because I can't.  Alternatively, I could use PHP logic to inline-feed those values into the corresponding HTML element's style attribute and then significantly reduce the amount of coding required.  

I realize this is an oddball scenario, but I am curious about how to deal with interactive design.  Any advice would be welcomed!
j

**Comment by DoryAzar** [comment]
I have a couple of suggestions that come to mind:
1. Limit the use of colors to let's say 5. The number of colors doesn't really matter at this stage given that the form input type is the same (for this project at least). Create 10 different classes in your css with these color specs. Note that your class might need to encompass background colors, line and text colors to make sure you cover all the fields. 

2. Given what you are trying to achieve (user inputs impacting the style), you could bring the dynamic css that is expected to be changed in the html either using the `<style></style>` blocks or even within the definition of your html elements `<div style="color: black;"></div>`. It might not be the best approach for code separation but for the sake of this project, it might be acceptable. @susanBuck to validate this option.

3. The third option - which I would do - is for your PHP logic to generate a CSS on the fly that would complement a default css linked in the HTML based on the inputs from the form. 
so your html would look something like the following:
```php
<link rel="stylesheet" href="default.css" />
<?php if($form_validated) : ?>
<link rel="stylesheet" href="addendum_template.php" />
<?php endif; ?>
```
Notice that the "addendum_template" is a PHP file but its header is changed to make it act like a css:
```php
<?php
/*** set the content type header to CSS ***/
header("Content-type: text/css");

$color1 = 'blue';

myBlueDiv {
   background-color: <?php echo $color1; ?>
}
```

**Comment by susanBuck** [comment]
I'd go with option 2 that @DoryAzar described. 

I think it warrants an exception to the rule of avoiding inline CSS, especially because it's not as if you're actually hard-coding the styles in the HTML (since the style is dynamically generated).

I've actually done something just like that in a project where a dominant color was programmatically selected from a users' profile photo, and then that color was used as the border of the photo. In that situation, the color options were nearly endless, so it was the most efficient solution.

The code looked something like this
```php
<img src='<?= $photoUrl ?>' class='profilePhoto'  style='border-color:<?= $color ?>'>
```

(Note that all other non-dynamic style properties (size, border width, etc.) were specified in the external CSS file under the `profilePhoto` class.)

Option 3 that Dorry described would work, but feels needlessly complex and still breaks separation of concerns (this time between logic and style).

**Comment by jessupjs** [comment]
Thanks @susanBuck and @DoryAzar!

I'll plan to pass in values directly to the style attribute.

Out of curiosity, for the program you referred to, what process did you use to define the dominant color?

**Comment by susanBuck** [comment]
@jessupjs - I used this code library: https://github.com/thephpleague/color-extractor

Later in the semester, we'll see how to use code packages like these.

**Comment by jessupjs** [comment]
@susanBuck thanks and I'll look forward to it!
