### ISSUE TITLE
Accessing data from file to show in form

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#45]
Hi,

I am working on our project 2, and I have put together form that is for dog food measurements. I have a checkbox section for puppy, adult, and senior, and I have a dropdown box that is for the different sizes of dogs in pounds. I am not sure how to return food measurements based on their size and age selection. I have the following array with the information. Any guidance is appreciated.
```php
<?php
$dogs = [
    'Puppy' => [
        'petSize' => ['0-15', '16-25', '26-40', '41-60', '61-80', '81-100', '101'],
        'foodAmount' => ['1/2', '1', '1.5', '2.5', '3.5', '4.5', '6'],
    ],
    'Adult' => [
        'petSize' => ['0-15', '16-25', '26-40', '41-60', '61-80', '81-100', '101'],
        'foodAmount' => ['1', '1.5', '2.5', '3.5', '4.5', '5.5', '6.5'],
    ],
    'Senior' => [
        'petSize' => ['0-15', '16-25', '26-40', '41-60', '61-80', '81-100', '101'],
        'foodAmount' => ['3/4', '1', '1.25', '2', '3', '4', '5'],

    ],
];
?>
```

**Comment by DoryAzar** [comment]
I second @mdeforest. It would make it easier for you to get the food amount by addressing it like this: `$dogs[‘Puppy’][‘0-15’]`. That would return the right foodAmount.

**Comment by dickblair** [comment]
Hi guys,  The advice I see here differs from the examples I see in w3 schools, which is like my go to place for all things front end.  There they suggest building multi-dimensional arrays like this:

$cars = array
  (
  array("Volvo",22,18),
  array("BMW",15,13),
  array("Saab",5,2),
  array("Land Rover",17,15)
  );

Is this acceptable or is there some benefit to the other ways?

**Comment by cpowell1** [comment]
@DoryAzar when you extract the food amount from they array as you did, do you think a for each loop would work? I am trying to determine the best way for boy the pet age and pet size to match to the correct food amount. My other thoughts were to use a conditional if statement to maybe specifically extract data for each instance (ie. selects Puppy, 0-15lbs, outputs 1/2 cup], but that seems like a lot of if statements to use.

**Comment by jessupjs** [comment]
@cpowell1 :: just seeing this, but it also might be worth waiting a day in case Wk4 presents object oriented programming and class construction.  In which case (and it may be required that you create classes for your project), you may want to construct classes, "Puppy", "Adult", "Senior", that share fields, "ageRange" and "foodMeasurements".  You could then instantiate and load each object into arrays "puppyList", "adultList" and "seniorList" with a FOR loop.  The search function would be another FOR loop but at least the data would be in the same place.

BUT I'm learning PHP too, so I could totally be suggesting the wrong approach!

**Comment by DoryAzar** [comment]
Let me make sure that I understand your use case. You are going to have a form where the user would choose the age of the dog (from a check box) and then from a dropdown they select the size. I imagine that they can choose multiple ages correct? so they could say for size 0-15 get me the food amount for Puppy, Adult and Senior. The system should return:
- Puppy: 1/2
- Adult: 1
- Senior: 3/4
Is that right?

If my understanding is correct then from the moment you submit your form through a get or a post (let's assume it's post for the sake of conversation) then if you do a `dump` on the $_POST, the output should look something like this:
```php
array(4)( ['Puppy'] => 'on', ['Adult'] => 'on', ['Senior'] => 'on', ['size'] => '0-15') 
```
Now in order for you to get the food amount, after validating the inputs all you need to do is:
1. Make sure you save the value of size in a variable and unset it from the post array. It would make it easier.
```php
$size = $_POST['size'];
unset($_POST['size']);
```
2. Now the $_POST array contains only the ages that you wanna compute the food amount for.Since you using checkboxes, only the values checked will be in $_POST. so I advise that you use `array_keys(nameofarray)`. This function takes only the keys of the array passed to it. so it will give you an array that has ['Puppy', 'Adult', 'Senior'] and if only Puppy and Senior were checked then only these two will be in the resulting array. So the code would look like this:
```php
$dogAges = array_keys($_POST);
```
3. Last step is computing the food amount from these inputs. I suggest you use array_map(function x, arrayname). array_map might be a little tricky to understand but once you grasp it, it's very useful. What it does is that it will apply function x to each element in arrayname and it will return the result in an array. This is exactly what you want. Your function is `function (x) { return $dogs[x][$size];}`. So the code would look something like:

```php
$result = array_map(function($x) { return $dogs[x][$size]; }, $dogAges);
```
remember that $dogs is the @mdeforest's array :).

And I think that if I got your application right, this should do it. Of course the code is not optimized and I don't recommend that you copy and paste it as is cause I have not tried it. But I hope the logic is sain.

**Comment by cpowell1** [comment]
When I do the dump for the $GET I get these results
```array(3) {
  ["petName"]=>
  string(6) "Peyton"
  ["size"]=>
  string(8) "Up to 15"
  ["petAge"]=>
  string(5) "Puppy"
}``` 

I am wondering if I am incorporating the array in the file wrong. I have it in a file called dogdata.php, and then in my calculate.php file, I use the get_file_contents().

**Comment by DoryAzar** [comment]
Any chance you can share what dogdata.php is? There is no easy way for me to understand if the`foreach` you are using works without knowing what your data is.

**Comment by ccrane** [comment]
@mdeforest Great recommendation!

**Comment by susanBuck** [comment]
FYI for anyone watching this thread - @cpowell1 and I debugged this via Slack.

She ended up using an array like the one @mdeforest suggested:
```php
# Our "table" of dog sizes to food amount
$dogs = [
    'Puppy' => [
        '0-15' => '1/2',
        '16-25' => '1',
        '26-40' => '1.5',
        '41-60' => '2.4',
        '61-80' => '3.5',
        '81-100' => '4.5',
        '101' => '6'
    ],
    'Adult' => [
        '0-15' => '1',
        '16-25' => '1.',
        '26-40' => '2.5',
        '41-60' => '3.5',
        '61-80' => '4.5',
        '81-100' => '5.5',
        '101' => '6+'
    ],
    'Senior' => [
        '0-15' => '1/2',
        '16-25' => '1',
        '26-40' => '2',
        '41-60' => '3',
        '61-80' => '4',
        '81-100' => '5',
        '101' => '5.5'
    ],
];
```

Then, given the values from the form data matched the indices used in the array, she was able to extract the desired value from the array like so:

```php
# Extract the data from the form
$petName = $_GET['petName'];
$size = $_GET['size'];
$petAge = $_GET['petAge'];

# Extract the food amount from our array
# Using the given pet age and given pet size
$result = $dogs[$petAge][$size];
 ```
