### ISSUE TITLE
No Data Returned

### ISSUE THREAD

**Issue by chantalthomas** [susanBuck/dwa15-fall2018#54]
Hello! 

So I am running into an issue with Sessions and trying to get my results of some calculations to display on the screen after the redirect. Before implemented the sessions piece, I tested that my functions were operating as expected, so I am pretty sure I am missing something with my sessions code. I am not receiving any error messages, my page appears to be refreshing without returning any data. Any help is greatly appreciated! 

```php
#storing data in the session
$_SESSION['result'] = [
    'feet' => $feet ,
    'inches' => $inches ,
    'weight' => $weight ,
    'age' => $age ,
    'gender' => $gender ,
    'exerciseAmount' => $exerciseAmount
];

#Redirect
header('Location: index.php');
```

```php
#logic.php content
session_start();

if(isset($_SESSION['results'])){
    $results = $_SESSION['results'];

    $feet = $results['feet'];
    $inches = $results['inches'];
    $weight = $results['weight'];
    $age = $results['age'];
    $gender = $results['gender'];
    $exerciseAmount = $results['exerciseAmount'];
}

session_unset();
```

```php
#code used to output results in index.php
<?php if (isset($_GET['submit'])): ?>
        Your caloric intake is: <?php echo mifflinEquation($weight, $feet, $inches, $age); ?>
    <?php endif; ?>
```
http://p2.dwafall18.me/

**Comment by jessupjs** [comment]
Hi Chantal!

Just a quick look, but uncertain if this will fix it:  

You entered: 
`#storing data in the session`
`$_SESSION['result'] = [`

But may want to correct to:
`#storing data in the session`
`$_SESSION['results'] = [`

Good luck!

**Comment by chantalthomas** [comment]
@jessupjs good catch! I corrected that and still no luck.

I will look further into whether i'm storing the data correctly. Another possibility is that I am not calling the my function correctly after the data has been submitted.

```php
<?php if (isset($_GET['submit'])): ?>
        Your caloric intake is: <?php echo mifflinEquation($weight, $feet, $inches, $age); ?>
    <?php endif; ?>
```

I'm trying to evaluate my function if data has been submitted.

**Comment by susanBuck** [comment]
@chantalthomas Do you have a `session_start();` at the top of the file that sets the session values? (It's not shown in the snippet you shared, but it may actually be in your file - so just wanted to double check)

**Comment by chantalthomas** [comment]
Hi @susanBuck, I do!

I think the issue that I am facing now is with a external function that I am trying to call in my display file.  I tested just outputting one of the stored value to the site and it is working. When I try to call the function I am getting the following error message in the inspect view.

<img width="1440" alt="screen shot 2018-10-01 at 9 18 04 pm" src="https://user-images.githubusercontent.com/16106162/46324077-adcb3000-c5bf-11e8-8539-3b3436a85b5e.png">

**Comment by susanBuck** [comment]
@chantalthomas Could you update your github repo with the latest and share the URL? I can run it on my end to test.

**Comment by chantalthomas** [comment]
@susanBuck I have pushed my recent changes to my repo. And here is my project url.

Note: I commented out a line of code that causes the HTTP 500 error. 

```php
#require 'calculateCaloricIntake.php';
```
This line is in my index.php file

**Comment by susanBuck** [comment]
You're on the right track regarding calling a function that is not available. 

In `index.php` you invoke `mifflinEquation` which exists in the file `calculateCaloricIntake.php`, but this file is not imported into `index.php`.

One solution, as you've noted, is to try and make it available by importing `calculateCaloricIntake.php`. However, this is problematic because `calculateCaloricIntake.php` contains a redirect that redirects to `index.php`:

```php
header('Location: index.php');
```

...so if you include it in `index.php` this will cause an endless loop of redirects. This is likely why you're getting the 500 server error.

To fix the problem, rather than importing `calculateCaloricIntake.php`, I suggest the following re-organization.

## Reorganization
First, it would be better if `mifflinEquation` was not actually invoked in the display file. Instead, invoke it in one of your logic files, and make the results available for the display file.

For example, in your form processing script (`calculateCaloricIntake.php`) you could add a new value to the session called `caloricIntake` that stores the results of `mifflinEquation`:

```php
#storing data in the session
$_SESSION['results'] = [
    'feet' => $feet ,
    'inches' => $inches ,
    'weight' => $weight ,
    'age' => $age ,
    'gender' => $gender ,
    'exerciseAmount' => $exerciseAmount,
    'caloricIntake' => mifflinEquation($weight, $feet, $inches, $age), # <--- NEW
];
```

Because the `mifflinEquation` function is defined in this same file, it should work.

Then, in `logic.php`, when you're extracting the data from the session, be sure to include this value as well:

```php
if(isset($_SESSION['results'])){
    $results = $_SESSION['results'];
    
    # [... redacted for brevity ...]

    $caloricIntake = $results['caloricIntake']; # <---- NEW
}
```

Finally, your display file only needs to worry about displaying the result if it has it:

```php
<?php if (isset($caloricIntake)): ?>
    Your caloric intake is: <?= $caloricIntake ?>
<?php endif; ?>
```

**Comment by chantalthomas** [comment]
Yippieeeeee! That was it! it is working now! Thank you so much!

**Comment by susanBuck** [comment]
No problem! Good luck wrapping up the rest of your project!
