### ISSUE TITLE
Modifying Form.php

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#56]
Good evening!

I realize that we have the option of extending Form.php with a MyForm.php, but is it also acceptable to modify Form.php directly?  For example, if I'd like to change the validate output so that it uses a more readable term than `$fieldname`, could I?  Less mild examples might included paring unused methods or adding absent / case-specific methods. 

More broadly, in terms of handling code written by others responsibly, as we use sourced classes, is there a common etiquette (or perhaps formal protocol) for handling revisions?

Thanks!

**Comment by susanBuck** [comment]
When utilizing outside code (and my providing `Form.php` for you is an example of that), it's generally best to avoid changing that code directly. If the developer of the outside code releases updates, it makes it difficult to update your version because you then have changes in it.

Even with `Form.php` and this controlled course environment, there have been instances in past semesters where I've discovered a bug and have instructed students to replace the class with an updated version.

All that being said, I think it's okay to make an exception here if you really want to explore with making your own edits to `Form.php`, especially if you find it helpful in giving you practice with writing code within the context of a class. Just be aware of the downsides of doing that, especially when moving into more complex projects that utilize real-world external code libraries.

**Comment by susanBuck** [comment]
Test

**Comment by faisalbaz** [comment]
Thank you for updates. I will follow these when deploying on digital ocean.

Vr
Faisal Baz

**Comment by jessupjs** [comment]
Thanks @susanBuck!  I ended up extending so that I wouldn't disturb your work.  I spent some time trying going through the `validate()` method in `Form.php`, and for comparing values from different form names, I had to sort of do some ducktape work that I'd be interested if some has a more elegant solution for.

In my logic file, wanted to compare four related form values: 

```
if ($face == "none" && $nose == "none" && $lips == "none" && $eyes == "none") {
    $matchless = "face";
    $notNone = "cdyn";
} else if ($face == $nose || $face == $lips || $face == $eyes) {
    $matchless = "cdym";
    $notNone = "face";
} else {
    $matchless = "face";
    $notNone = "face";
}
```

which I used to manipulate `validate()`:

```
$errors = $myForm->validateCustom(
   [
        'lsn' => 'requiredCustom1',
        $notNone => 'notNoneCustom1',
        $matchless => 'matchlessCustom1'
    ]
);
```

Draft code can be found at [Github](https://github.com/jessupjs/p2) and [my production site](http://p2.jjessup.me/).
