### ISSUE TITLE
Redirecting back to index.php for validation

### ISSUE THREAD

**Issue by malrice** [susanBuck/dwa15-fall2018#58]
Hello, 
The last bit of my Project 2 work involves a form that forwards to a confirmation page upon submission. For the validation process, I would need to redirect back to the main page in order for the visitor to fix any errors. I'm at a bit of a standstill on how to do this. I've tried doing an if/else statement such as this: 

if($hasErrors){
header('index.php');}
else{header('search.php');}

(please note that coding is approximate, as I don't have the file open). 
This didn't work, giving me an error. 
I'm wondering if this is the best course of action, or if there's a better course of action I should pursue.

**Comment by jessupjs** [comment]
HI @malrice, I may not be the best person to help you, but at least one that is still up - is your git repo up-to-date for a closer look?

**Comment by DoryAzar** [comment]
@malrice that seems to be the right logic. You said the code is approximate... just make sure to use the header function correctly. `header(‘Location: index.php’)`
Like @jessupjs says, snaps of your code would help or if you can point us to your right place in your code so that we could help.

**Comment by malrice** [comment]
Here's what I have so far: 
if ($errors) {
    header('Location:index.php');
} else {
    header('Location:search.php');
}
 The new problem is that it will only re-direct back to the index.php, not continue onto search.php even when the conditions are met.

**Comment by DoryAzar** [comment]
Getting closer then...You will need to investigate why $errors is not returning false.
Your code on github does not seem to be up to date. You wanna update it so that we help you debug?

**Comment by malrice** [comment]
My files should be updated now. Currently the error reporting section is on the logic.php page, starting at line 25. It should redirect back to index.php if there's nothing in the name/'reservation' field on index.php, and redirect to search.php if the name is filled in.

**Comment by malrice** [comment]
Sorry, i need to do a quick git fix. My p2 repository will be down for a few minutes.

**Comment by DoryAzar** [comment]
is it ok if I clone your project locally?

**Comment by malrice** [comment]
Go right ahead!

**Comment by DoryAzar** [comment]
@malrice I am working on it. 
1. The first thing that you need to fix is how you are checking for errors.
The validate form function returns an array. So if you really want to check whether there are errors in 'reservation' you will need to check if `!empty($errors)` as opposed to `$errors` (as a boolean). Otherwise, you will need to use the hasErrors from the Form class. 
2. There is a little bit of a logic loop happening. The index form submits to search.php. However search.php calls for logic.php. So every time search.php loads it s going to execute the code in logic.php. But logic.php is also redirecting to search.php (which calls on logic.php)...you see the loop there? this is why the browser is not interpreting this correctly. You will need to fix this logic. I will look more into to see if I can come up with more constructive feedback about it

**Comment by DoryAzar** [comment]
Ok. fixed:
- Copy this code right after `$form = new Form($_GET);`
- Notice how you don't need an else to redirect to search.php, cause you are in it already. So the code will continue to execute if there are no errors.

```php
#Error reporting
$errors = $form->validate([
    'reservation' => 'required|alphaNumeric'
]);

if (!empty($errors)) {
    header('Location: index.php');
}
```

**Comment by malrice** [comment]
It works! Thank you for your help. I always forget that checking for nothing is an option. Now to clean up the rest of my code before submitting!
