### ISSUE TITLE
Question about cache permission troubleshooting

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#66]
I have a quick point of clarification about the troubleshooting instructions for the cache permission issue when using composer to create a new laravel app (at the bottom of these notes: https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/new-laravel-app.md). It says to run the command that recursively sets us as the owner of the composer directory. I just wanted to confirm that means we don't need to re-run the composer create-project command.

**Comment by susanBuck** [comment]
Nope, you do not need to re-run the composer create-project command.

The create-project command should have successfully run, even if Composer was not able to write to the  cache. 

Fixing the cache writing issues just makes it so that future downloads can be written to the cache, which can improve the performance of Composer.

**Comment by mihika-shilpi** [comment]
Is there any way to check that the cache permission change is in effect?

**Comment by susanBuck** [comment]
@mihika-shilpi You could run the create-project command again, using a different project name, then just delete the resulting project directory when it's done

Test:
```
composer create-project laravel/laravel TEST "5.7.*" --prefer-dist
```

Remove when done:
```
rm -rf TEST
```
