### ISSUE TITLE
HTML elements :: best practice

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#7]
Good morning!

You mentioned in your first video for Assignment 2 that you'd like to see us appropriately use semantic HTML (for example replacing the generic `<div>` with a more context-specific `<header>`).  Are there any references or resources for helping to understand best practices for selecting the right element when there are more ambiguous options (for example replacing the generic `<div>` with the generic `<section>`)?  

Your example explanation about coding to aid of a screen reader also helped me to appreciate the "WHY" btw.  Thanks!

**Comment by susanBuck** [comment]
Hi @jessupjs -

Here's a good resource for deciding what "sectioning" type HTML element to use: [HTML5 Element Flowchart](http://html5doctor.com/downloads/h5d-sectioning-flowchart.pdf)

Glad the "why" behind it helped things click!

**Comment by jessupjs** [comment]
Thanks - honestly I've just been using `<div>`s because I was resetting most elements anyways and using class or id names to give them identity. 

Quick follow-up: does html syntax also effect web crawling?

**Comment by susanBuck** [comment]
Can you elaborate on what you mean by HTML syntax? 
I.e. are we talking code indentation, lowercase vs. uppercase tags, etc.? or something else?

**Comment by jessupjs** [comment]
I'm sorry - I should have said semantic HTML.  For example, does using a more specific element like `<article>` improve readability and ranking for SEO purposes?

Many thanks!
j

**Comment by DoryAzar** [comment]
W3C (governed by Tim Berner-Lee himself - creator of the web) tries to keep a standard for writing client code (HTML, CSS, JS). The standard is at its 5th version now...You probably heard a lot about HTML5 and so on. Well...it is a standard that evolves constantly to embrace all the advancements that people/companies come up with... Adhering to standards, especially in open languages such as these, is down the road beneficial because everybody inherits all the advancements that the community brings to it. Whether it's from an SEO perspective, Accessibility perspective, Shareability etc...
But at the end of the day it is just standard.

**Comment by susanBuck** [comment]
@jessupjs Yup, proper tags definitely helps for SEO purposes! Crawlers depend a lot on semantic tags to provide context for the content it's indexing.

**Comment by jessupjs** [comment]
Tks!
j
