### ISSUE TITLE
where to put logic code in laravel?

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#79]
Hi,

Where to put logic code in laravel application? or is it part of next lecture?

Thanks
Hemant

**Comment by DoryAzar** [comment]
I personally put my Objects/Classes under the app folder in a folder that i created. Those classes can automatically be used anywhere.

Just make sure to you define the namespace correctly for them: App\Your Folder.

And upon use in your controllers, make sure you do: `use App\Your folder\Classname`

**Comment by hemantbajpai** [comment]
thanks

**Comment by susanBuck** [comment]
We will start digging into the logic in Week 8 when we talk about forms and I'll show form processing.

We will begin by building our logic in the controllers. 

As the semester progresses, we'll look at other places that logic will go. For example, database related logic will be built into class files called Models.

I'll also touch upon building other classes to organize your logic code (similar to what @DoryAzar described) so that controllers don't get overly complex. As we learn more, we'll ultimately want  controllers to just handle the receiving of requests, initializing validation, outsourcing the real work to the appropriate class, then returning a response.
