### ISSUE TITLE
Subdomains on DO Production Server

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#8]
Hello!

So I was successful in getting my "hello-world" page up, but I'm having difficulty with the subdomain.  If I visit the [hello-world subdirectory](http://jjessup.me/hello-world/), all works well.  However when I attempt to use [hello-world subdomain](http://hello-world.jjessup.me) (or any other subdomain), the browser cannot find the site.

Attached is a screenshot of my DNS settings, and I did use the wildcard `*` for all CNAME records.  
<img width="1127" alt="screen shot 2018-09-13 at 5 13 14 pm" src="https://user-images.githubusercontent.com/36556988/45516969-bd9ee380-b77a-11e8-827b-100c7efadf99.png">

I must be missing a piece of the puzzle here, and the only difference I've noticed from the Notes to my own setup is that when I entered my IP address and looked through the listing of `/var/www/html/` that my `index.html` has a different appearance (no big deal - I think) and that there is no `info.php` file.

Any advice would be v much appreciated!

**Comment by DoryAzar** [comment]
I looked into it. I am personally using godaddy as my domain registrar so I had to check the documentation on how to do it for Digital Ocean. It worked perfectly fine for me.

They do have instructions for NameCheap on the DigitalOcean side and I think they are allowing a better integration since not a long ago.
Copying @susanBuck for testing this approach. 
**The wildcards and the apex need to be done at the Droplet side in Digital Ocean now**. On the Registrar side the digitalocean namespaces need to be provided: 
- [On the Registrar side](https://www.digitalocean.com/community/tutorials/how-to-point-to-digitalocean-nameservers-from-common-domain-registrars)
- [On the Droplet side](https://www.digitalocean.com/docs/networking/dns/quickstart/)

**Comment by jessupjs** [comment]
Thanks @DoryAzar for looking into this, and I'm glad you got yours up and running!

I was able to get my NameCheap domain to hosted on DigitalOcean, which I presume means that the A Record is directing to the root domain (`@`).  My concern is that either the NameCheap CNAME is not properly setup to allow subdomains or that the load balancer is not setup properly through DigitalOcean.  I kinda suspect the latter is my issue, but I suddenly I also wonder if my SSH configuration could cause an problem.  I'll keep investigating but many thanks!
j

**Comment by susanBuck** [comment]
Hey @jessupjs - As of this writing, It appears `http://hello-world.jjessup.me` is working. Either you fixed something, or it was just a DNS caching issue that resolved itself.

Also, just to follow up on @DoryAzar's notes (and helpful links) - those instructions are only applicable *if* you're using DigitalOcean's nameservers.

You may be, and that's fine, but if you're following the procedures I showed, I am not using DigitalOcean's nameservers, so there's no need to change any DNS related settings in DigitalOcean.

**Comment by DoryAzar** [comment]
@susanBuck thanks for the assessment. I had to go that route given that I have a parked domain with goDaddy that I could use. I did not explore doing it from the goDaddy side. Do you think it is ok to continue down that path or am I gonna hit some roadblocks down the road?

**Comment by susanBuck** [comment]
@DoryAzar You should be fine to continue with how you've set it up; I don't anticipate any roadblocks.

**Comment by DoryAzar** [comment]
@susanBuck Thank you!

**Comment by chantalthomas** [comment]
Just wanted to throw in my two cents for people that might be troubleshooting why their domain name is not visible on the production server... I mistakenly cloned my repo on the root directory instead of /var/www/html/. If you're running into issues checking the location of your repo, could be a good first crack at resolving the issue.

Also, should I now delete those files from the root? Any heavy cons to leaving the files in the wrong location? Now that my files are also in /var/www/html/ I am able to access hello-world on my prod server.

**Comment by susanBuck** [comment]
@chantalthomas I'd go ahead and delete the files you accidentally cloned to /root. They won't cause any harm, but they're just taking up space and could cause confusion down the road.

**Comment by chantalthomas** [comment]
@susanBuck  good to know! Thank you

**Comment by jessupjs** [comment]
@susanBuck :: that was a happy surprise!

Unless there is an objection, I'll leave the forum open to see if there are any related issues.

**Comment by satyapalvadi** [comment]
Just for some info - It took ~10 minutes for my domain name to propagate over the NC servers.

**Comment by susanBuck** [comment]
I think we can go ahead and close this now. If anyone else is having a similar issue, feel free to start a new thread!
