### ISSUE TITLE
phpstorm warning message - can not resolve directory

### ISSUE THREAD

**Issue by pausman** [susanBuck/dwa15-fall2018#84]
PHPstorm is giving the warning "can not resolve directory" on the line below. Everything works fine but the how can I get rid of the warning
 ``` 
    <!-- form to get the parameters to encode by-->
    <form method='GET' action='/caesar/encode-process'>

**Comment by susanBuck** [comment]
This is a built-in "inspection" PhpStorm has for HTML. Because of how URLs/directories typically work in a static site, it's looking or a file at `/caesar/encode-process/index.html\php` - but because we're using routing that obviously does not exist.

I'm not aware of any ways to inform the HTML inspection about the routing of Laravel (similar to what we did with the laravel-ide-helper), but I can tell you how to disable the warning.

Goto your preferences, *Editor* > *Inspections* > *HTML* and uncheck *File reference problems*

![image](https://user-images.githubusercontent.com/237711/47798420-b7e76800-dcfe-11e8-9ffc-797187209a3b.png)

Note from the screenshot how this can be a project specific setting, or something global to phpstorm. If you work on sites w/o routing, I suggest not making it a global change, because the inspection can be useful in those contexts.

**Comment by susanBuck** [comment]
Ref: #85
